// DO NOT EDIT. generated by webtyp.com/ormc

package businesscalendar

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type BusinessHours struct {
	Id        string
	DayOfWeek int64
	OpenMin   int64
	CloseMin  int64
	IsOpen    bool
	Notes     string
	UpdatedAt int64
}

func (m *BusinessHours) ModelName() string { return "business_hours" }

func (m *BusinessHours) Schema() []model.Field { return BusinessHoursModel.Fields }

func (m *BusinessHours) Pointers() []any {
	return []any{&m.Id, &m.DayOfWeek, &m.OpenMin, &m.CloseMin, &m.IsOpen, &m.Notes, &m.UpdatedAt}
}

func (m *BusinessHours) IsNil() bool { return m == nil }

func (m *BusinessHours) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("day_of_week", m.DayOfWeek)
	w.Int("open_min", m.OpenMin)
	w.Int("close_min", m.CloseMin)
	w.Bool("is_open", m.IsOpen)
	w.String("notes", m.Notes)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *BusinessHours) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.Int("day_of_week"); ok {
		m.DayOfWeek = v
	}
	if v, ok := r.Int("open_min"); ok {
		m.OpenMin = v
	}
	if v, ok := r.Int("close_min"); ok {
		m.CloseMin = v
	}
	if v, ok := r.Bool("is_open"); ok {
		m.IsOpen = v
	}
	if v, ok := r.String("notes"); ok {
		m.Notes = v
	}
	if v, ok := r.Int("updated_at"); ok {
		m.UpdatedAt = v
	}
}

type BusinessHoursList []*BusinessHours

func (s *BusinessHoursList) Schema() []model.Field  { return nil }
func (s *BusinessHoursList) Pointers() []any        { return nil }
func (s *BusinessHoursList) Len() int               { return len(*s) }
func (s *BusinessHoursList) At(i int) model.Fielder { return (*s)[i] }
func (s *BusinessHoursList) Append() model.Fielder {
	v := &BusinessHours{}
	*s = append(*s, v)
	return v
}
func (s *BusinessHoursList) IsNil() bool                      { return s == nil }
func (s *BusinessHoursList) EncodeFields(_ model.FieldWriter) {}
func (s *BusinessHoursList) DecodeFields(_ model.FieldReader) {}

func (m *BusinessHours) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var BusinessHours_ = struct {
	Id        string
	DayOfWeek string
	OpenMin   string
	CloseMin  string
	IsOpen    string
	Notes     string
	UpdatedAt string
}{
	Id:        "id",
	DayOfWeek: "day_of_week",
	OpenMin:   "open_min",
	CloseMin:  "close_min",
	IsOpen:    "is_open",
	Notes:     "notes",
	UpdatedAt: "updated_at",
}

func ReadOneBusinessHours(qb *orm.QB, model *BusinessHours) (*BusinessHours, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllBusinessHours(qb *orm.QB) (BusinessHoursList, error) {
	var results BusinessHoursList
	err := qb.ReadAll(
		func() model.Model { return &BusinessHours{} },
		func(m model.Model) { results = append(results, m.(*BusinessHours)) },
	)
	return results, err
}

type Holiday struct {
	Id           string
	SpecificDate int64
	Name         string
	Notes        string
	UpdatedAt    int64
}

func (m *Holiday) ModelName() string { return "holiday" }

func (m *Holiday) Schema() []model.Field { return HolidayModel.Fields }

func (m *Holiday) Pointers() []any {
	return []any{&m.Id, &m.SpecificDate, &m.Name, &m.Notes, &m.UpdatedAt}
}

func (m *Holiday) IsNil() bool { return m == nil }

func (m *Holiday) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("specific_date", m.SpecificDate)
	w.String("name", m.Name)
	w.String("notes", m.Notes)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *Holiday) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.Int("specific_date"); ok {
		m.SpecificDate = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
	if v, ok := r.String("notes"); ok {
		m.Notes = v
	}
	if v, ok := r.Int("updated_at"); ok {
		m.UpdatedAt = v
	}
}

type HolidayList []*Holiday

func (s *HolidayList) Schema() []model.Field            { return nil }
func (s *HolidayList) Pointers() []any                  { return nil }
func (s *HolidayList) Len() int                         { return len(*s) }
func (s *HolidayList) At(i int) model.Fielder           { return (*s)[i] }
func (s *HolidayList) Append() model.Fielder            { v := &Holiday{}; *s = append(*s, v); return v }
func (s *HolidayList) IsNil() bool                      { return s == nil }
func (s *HolidayList) EncodeFields(_ model.FieldWriter) {}
func (s *HolidayList) DecodeFields(_ model.FieldReader) {}

func (m *Holiday) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Holiday_ = struct {
	Id           string
	SpecificDate string
	Name         string
	Notes        string
	UpdatedAt    string
}{
	Id:           "id",
	SpecificDate: "specific_date",
	Name:         "name",
	Notes:        "notes",
	UpdatedAt:    "updated_at",
}

func ReadOneHoliday(qb *orm.QB, model *Holiday) (*Holiday, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllHoliday(qb *orm.QB) (HolidayList, error) {
	var results HolidayList
	err := qb.ReadAll(
		func() model.Model { return &Holiday{} },
		func(m model.Model) { results = append(results, m.(*Holiday)) },
	)
	return results, err
}

type Closure struct {
	Id           string
	SpecificDate int64
	Reason       string
	UpdatedAt    int64
}

func (m *Closure) ModelName() string { return "closure" }

func (m *Closure) Schema() []model.Field { return ClosureModel.Fields }

func (m *Closure) Pointers() []any { return []any{&m.Id, &m.SpecificDate, &m.Reason, &m.UpdatedAt} }

func (m *Closure) IsNil() bool { return m == nil }

func (m *Closure) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("specific_date", m.SpecificDate)
	w.String("reason", m.Reason)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *Closure) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.Int("specific_date"); ok {
		m.SpecificDate = v
	}
	if v, ok := r.String("reason"); ok {
		m.Reason = v
	}
	if v, ok := r.Int("updated_at"); ok {
		m.UpdatedAt = v
	}
}

type ClosureList []*Closure

func (s *ClosureList) Schema() []model.Field            { return nil }
func (s *ClosureList) Pointers() []any                  { return nil }
func (s *ClosureList) Len() int                         { return len(*s) }
func (s *ClosureList) At(i int) model.Fielder           { return (*s)[i] }
func (s *ClosureList) Append() model.Fielder            { v := &Closure{}; *s = append(*s, v); return v }
func (s *ClosureList) IsNil() bool                      { return s == nil }
func (s *ClosureList) EncodeFields(_ model.FieldWriter) {}
func (s *ClosureList) DecodeFields(_ model.FieldReader) {}

func (m *Closure) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Closure_ = struct {
	Id           string
	SpecificDate string
	Reason       string
	UpdatedAt    string
}{
	Id:           "id",
	SpecificDate: "specific_date",
	Reason:       "reason",
	UpdatedAt:    "updated_at",
}

func ReadOneClosure(qb *orm.QB, model *Closure) (*Closure, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllClosure(qb *orm.QB) (ClosureList, error) {
	var results ClosureList
	err := qb.ReadAll(
		func() model.Model { return &Closure{} },
		func(m model.Model) { results = append(results, m.(*Closure)) },
	)
	return results, err
}

type UpsertBusinessHoursArgs struct {
	DayOfWeek int64
	OpenMin   int64
	CloseMin  int64
	IsOpen    bool
	Notes     string
}

func (m *UpsertBusinessHoursArgs) ModelName() string { return "upsert_business_hours_args" }

func (m *UpsertBusinessHoursArgs) Schema() []model.Field { return UpsertBusinessHoursArgsModel.Fields }

func (m *UpsertBusinessHoursArgs) Pointers() []any {
	return []any{&m.DayOfWeek, &m.OpenMin, &m.CloseMin, &m.IsOpen, &m.Notes}
}

func (m *UpsertBusinessHoursArgs) IsNil() bool { return m == nil }

func (m *UpsertBusinessHoursArgs) EncodeFields(w model.FieldWriter) {
	w.Int("day_of_week", m.DayOfWeek)
	w.Int("open_min", m.OpenMin)
	w.Int("close_min", m.CloseMin)
	w.Bool("is_open", m.IsOpen)
	w.String("notes", m.Notes)
}

func (m *UpsertBusinessHoursArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("day_of_week"); ok {
		m.DayOfWeek = v
	}
	if v, ok := r.Int("open_min"); ok {
		m.OpenMin = v
	}
	if v, ok := r.Int("close_min"); ok {
		m.CloseMin = v
	}
	if v, ok := r.Bool("is_open"); ok {
		m.IsOpen = v
	}
	if v, ok := r.String("notes"); ok {
		m.Notes = v
	}
}

type UpsertBusinessHoursArgsList []*UpsertBusinessHoursArgs

func (s *UpsertBusinessHoursArgsList) Schema() []model.Field  { return nil }
func (s *UpsertBusinessHoursArgsList) Pointers() []any        { return nil }
func (s *UpsertBusinessHoursArgsList) Len() int               { return len(*s) }
func (s *UpsertBusinessHoursArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *UpsertBusinessHoursArgsList) Append() model.Fielder {
	v := &UpsertBusinessHoursArgs{}
	*s = append(*s, v)
	return v
}
func (s *UpsertBusinessHoursArgsList) IsNil() bool                      { return s == nil }
func (s *UpsertBusinessHoursArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *UpsertBusinessHoursArgsList) DecodeFields(_ model.FieldReader) {}

func (m *UpsertBusinessHoursArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetDayBoundsArgs struct {
	Date int64
}

func (m *GetDayBoundsArgs) ModelName() string { return "get_day_bounds_args" }

func (m *GetDayBoundsArgs) Schema() []model.Field { return GetDayBoundsArgsModel.Fields }

func (m *GetDayBoundsArgs) Pointers() []any { return []any{&m.Date} }

func (m *GetDayBoundsArgs) IsNil() bool { return m == nil }

func (m *GetDayBoundsArgs) EncodeFields(w model.FieldWriter) {
	w.Int("date", m.Date)
}

func (m *GetDayBoundsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("date"); ok {
		m.Date = v
	}
}

type GetDayBoundsArgsList []*GetDayBoundsArgs

func (s *GetDayBoundsArgsList) Schema() []model.Field  { return nil }
func (s *GetDayBoundsArgsList) Pointers() []any        { return nil }
func (s *GetDayBoundsArgsList) Len() int               { return len(*s) }
func (s *GetDayBoundsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetDayBoundsArgsList) Append() model.Fielder {
	v := &GetDayBoundsArgs{}
	*s = append(*s, v)
	return v
}
func (s *GetDayBoundsArgsList) IsNil() bool                      { return s == nil }
func (s *GetDayBoundsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetDayBoundsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetDayBoundsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListHolidaysArgs struct {
	From int64
	To   int64
}

func (m *ListHolidaysArgs) ModelName() string { return "list_holidays_args" }

func (m *ListHolidaysArgs) Schema() []model.Field { return ListHolidaysArgsModel.Fields }

func (m *ListHolidaysArgs) Pointers() []any { return []any{&m.From, &m.To} }

func (m *ListHolidaysArgs) IsNil() bool { return m == nil }

func (m *ListHolidaysArgs) EncodeFields(w model.FieldWriter) {
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *ListHolidaysArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("from"); ok {
		m.From = v
	}
	if v, ok := r.Int("to"); ok {
		m.To = v
	}
}

type ListHolidaysArgsList []*ListHolidaysArgs

func (s *ListHolidaysArgsList) Schema() []model.Field  { return nil }
func (s *ListHolidaysArgsList) Pointers() []any        { return nil }
func (s *ListHolidaysArgsList) Len() int               { return len(*s) }
func (s *ListHolidaysArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListHolidaysArgsList) Append() model.Fielder {
	v := &ListHolidaysArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListHolidaysArgsList) IsNil() bool                      { return s == nil }
func (s *ListHolidaysArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListHolidaysArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListHolidaysArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type AddHolidayArgs struct {
	SpecificDate int64
	Name         string
	Notes        string
}

func (m *AddHolidayArgs) ModelName() string { return "add_holiday_args" }

func (m *AddHolidayArgs) Schema() []model.Field { return AddHolidayArgsModel.Fields }

func (m *AddHolidayArgs) Pointers() []any { return []any{&m.SpecificDate, &m.Name, &m.Notes} }

func (m *AddHolidayArgs) IsNil() bool { return m == nil }

func (m *AddHolidayArgs) EncodeFields(w model.FieldWriter) {
	w.Int("specific_date", m.SpecificDate)
	w.String("name", m.Name)
	w.String("notes", m.Notes)
}

func (m *AddHolidayArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("specific_date"); ok {
		m.SpecificDate = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
	if v, ok := r.String("notes"); ok {
		m.Notes = v
	}
}

type AddHolidayArgsList []*AddHolidayArgs

func (s *AddHolidayArgsList) Schema() []model.Field  { return nil }
func (s *AddHolidayArgsList) Pointers() []any        { return nil }
func (s *AddHolidayArgsList) Len() int               { return len(*s) }
func (s *AddHolidayArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *AddHolidayArgsList) Append() model.Fielder {
	v := &AddHolidayArgs{}
	*s = append(*s, v)
	return v
}
func (s *AddHolidayArgsList) IsNil() bool                      { return s == nil }
func (s *AddHolidayArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *AddHolidayArgsList) DecodeFields(_ model.FieldReader) {}

func (m *AddHolidayArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RemoveHolidayArgs struct {
	Id string
}

func (m *RemoveHolidayArgs) ModelName() string { return "remove_holiday_args" }

func (m *RemoveHolidayArgs) Schema() []model.Field { return RemoveHolidayArgsModel.Fields }

func (m *RemoveHolidayArgs) Pointers() []any { return []any{&m.Id} }

func (m *RemoveHolidayArgs) IsNil() bool { return m == nil }

func (m *RemoveHolidayArgs) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
}

func (m *RemoveHolidayArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type RemoveHolidayArgsList []*RemoveHolidayArgs

func (s *RemoveHolidayArgsList) Schema() []model.Field  { return nil }
func (s *RemoveHolidayArgsList) Pointers() []any        { return nil }
func (s *RemoveHolidayArgsList) Len() int               { return len(*s) }
func (s *RemoveHolidayArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *RemoveHolidayArgsList) Append() model.Fielder {
	v := &RemoveHolidayArgs{}
	*s = append(*s, v)
	return v
}
func (s *RemoveHolidayArgsList) IsNil() bool                      { return s == nil }
func (s *RemoveHolidayArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *RemoveHolidayArgsList) DecodeFields(_ model.FieldReader) {}

func (m *RemoveHolidayArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListClosuresArgs struct {
	From int64
	To   int64
}

func (m *ListClosuresArgs) ModelName() string { return "list_closures_args" }

func (m *ListClosuresArgs) Schema() []model.Field { return ListClosuresArgsModel.Fields }

func (m *ListClosuresArgs) Pointers() []any { return []any{&m.From, &m.To} }

func (m *ListClosuresArgs) IsNil() bool { return m == nil }

func (m *ListClosuresArgs) EncodeFields(w model.FieldWriter) {
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *ListClosuresArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("from"); ok {
		m.From = v
	}
	if v, ok := r.Int("to"); ok {
		m.To = v
	}
}

type ListClosuresArgsList []*ListClosuresArgs

func (s *ListClosuresArgsList) Schema() []model.Field  { return nil }
func (s *ListClosuresArgsList) Pointers() []any        { return nil }
func (s *ListClosuresArgsList) Len() int               { return len(*s) }
func (s *ListClosuresArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListClosuresArgsList) Append() model.Fielder {
	v := &ListClosuresArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListClosuresArgsList) IsNil() bool                      { return s == nil }
func (s *ListClosuresArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListClosuresArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListClosuresArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type AddClosureArgs struct {
	SpecificDate int64
	Reason       string
}

func (m *AddClosureArgs) ModelName() string { return "add_closure_args" }

func (m *AddClosureArgs) Schema() []model.Field { return AddClosureArgsModel.Fields }

func (m *AddClosureArgs) Pointers() []any { return []any{&m.SpecificDate, &m.Reason} }

func (m *AddClosureArgs) IsNil() bool { return m == nil }

func (m *AddClosureArgs) EncodeFields(w model.FieldWriter) {
	w.Int("specific_date", m.SpecificDate)
	w.String("reason", m.Reason)
}

func (m *AddClosureArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("specific_date"); ok {
		m.SpecificDate = v
	}
	if v, ok := r.String("reason"); ok {
		m.Reason = v
	}
}

type AddClosureArgsList []*AddClosureArgs

func (s *AddClosureArgsList) Schema() []model.Field  { return nil }
func (s *AddClosureArgsList) Pointers() []any        { return nil }
func (s *AddClosureArgsList) Len() int               { return len(*s) }
func (s *AddClosureArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *AddClosureArgsList) Append() model.Fielder {
	v := &AddClosureArgs{}
	*s = append(*s, v)
	return v
}
func (s *AddClosureArgsList) IsNil() bool                      { return s == nil }
func (s *AddClosureArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *AddClosureArgsList) DecodeFields(_ model.FieldReader) {}

func (m *AddClosureArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RemoveClosureArgs struct {
	Id string
}

func (m *RemoveClosureArgs) ModelName() string { return "remove_closure_args" }

func (m *RemoveClosureArgs) Schema() []model.Field { return RemoveClosureArgsModel.Fields }

func (m *RemoveClosureArgs) Pointers() []any { return []any{&m.Id} }

func (m *RemoveClosureArgs) IsNil() bool { return m == nil }

func (m *RemoveClosureArgs) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
}

func (m *RemoveClosureArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type RemoveClosureArgsList []*RemoveClosureArgs

func (s *RemoveClosureArgsList) Schema() []model.Field  { return nil }
func (s *RemoveClosureArgsList) Pointers() []any        { return nil }
func (s *RemoveClosureArgsList) Len() int               { return len(*s) }
func (s *RemoveClosureArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *RemoveClosureArgsList) Append() model.Fielder {
	v := &RemoveClosureArgs{}
	*s = append(*s, v)
	return v
}
func (s *RemoveClosureArgsList) IsNil() bool                      { return s == nil }
func (s *RemoveClosureArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *RemoveClosureArgsList) DecodeFields(_ model.FieldReader) {}

func (m *RemoveClosureArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
